<<<<<<< HEAD
language: node_js
node_js:
- "10"
- node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls
=======
language: node_js
>>>>>>> 103829c2abb48cb0dbc759c0402007b9223a8c51
